# Generated by Django 3.2 on 2023-02-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wishlist',
        ),
    ]
