# Generated by Django 3.2 on 2023-02-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packages',
            options={'verbose_name_plural': 'Packages'},
        ),
        migrations.AddField(
            model_name='packages',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
