# Generated by Django 3.2 on 2023-01-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230112_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='product',
            name='for_sensory_needs',
            field=models.TextField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', max_length=1024),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
